name: master

on:
  workflow_dispatch

jobs:
  compile:
    runs-on: ubuntu-latest #${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        include:
#          - os: ubuntu-latest
#          - os: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      run: stack install

  dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download dependencies
      run: ./download_dependencies.sh

  download_datasets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download datasets
      run: |
        cd data
        python download_simple.py
        python download_roads.py

  process_datasets:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Process datasets
      run: |
        cd data
        ./crop_border.sh
        ./land_use.sh

  test:
    runs-on: ubuntu-latest
    needs: [compile, dependencies, download_datasets]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run program
      run: |
        echo 'asakareh\nasakareh_improved\nsuh\nsuh_improved\nwatson' > configs/run.txt
        ~/.local/bin/site-suitability
    - name: Test outputs
      run: |
        cd tests
        pytest -vvvv --log-cli-level=INFO test.py
